### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixops-aws#19] opened 2019-11-24 18:13 UTC
I'm working on a pull request for docs but couldn't build the documentation. Apologies if I'm missing something obvious:

```
~/code/nixops-aws/doc/manual > make    
xsltproc --nonet --param section.autolabel 1 --param section.label.includes.component.label 1 --param html.stylesheet \'style.css\' --param xref.with.number.and.title 0 --param toc.section.depth 3 --param admon.style \'\' --param callout.graphics.extension \'.gif\' --param contrib.inline.enabled 0 --xinclude --stringparam profile.condition manual \
  http://docbook.sourceforge.net/release/xsl-ns/current/profiling/profile.xsl manual.xml | \
  xsltproc --nonet --param section.autolabel 1 --param section.label.includes.component.label 1 --param html.stylesheet \'style.css\' --param xref.with.number.and.title 0 --param toc.section.depth 3 --param admon.style \'\' --param callout.graphics.extension \'.gif\' --param contrib.inline.enabled 0 --output manual.html http://docbook.sourceforge.net/release/xsl-ns/current/xhtml/docbook.xsl -
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl-ns/current/xhtml/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl-ns/current/xhtml/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl-ns/current/xhtml/docbook.xsl
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl-ns/current/profiling/profile.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl-ns/current/profiling/profile.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl-ns/current/profiling/profile.xsl
Makefile:16: recipe for target 'manual.html' failed
make: *** [manual.html] Error 4

**Comment by bhipple** [comment] 2020-03-15 19:13
The make also fails for me, and it looks like all of the AWS documentation is a duplicate of https://github.com/NixOS/nixops, which doesn't appear to have any logic for combining manuals out of plugins.

What's the structure here? Is the manual in this repo dead?  Should we delete all the XML files and targets to avoid confusion?

**Closed** 2020-03-15 20:41 UTC
